var MSG = {
  title: "BIPES Beta",
  blocks: "Bloques",
  linkTooltip: "Guarda conexión a los bloques.",
  runTooltip: "Ejecute el programa definido por los bloques en el área de trabajo.",
  badCode: "Error del programa:\n%1",
  timeout: "Se excedio el máximo de iteraciones ejecutadas permitidas.",
  trashTooltip: "Descartar todos los bloques.",
  catLogic: "Lógica",
  catLoops: "Secuencias",
  catMath: "Matemáticas",
  catText: "Texto",
  catLists: "Listas",
  catColour: "Color",
  catVariables: "Variables",
  catFunctions: "Funciones",
  listVariable: "lista",
  textVariable: "texto",
  httpRequestError: "Hubo un problema con la petición.",
  linkAlert: "Comparte tus bloques con este enlace:\n\n%1",
  hashError: "«%1» no corresponde con ningún programa guardado.",
  xmlError: "No se pudo cargar el archivo guardado.  ¿Quizá fue creado con otra versión de Blockly?",
  badXml: "Error de análisis XML:\n%1\n\nSelecciona OK para abandonar tus cambios o Cancelar para seguir editando el XML.",
  saveTooltip: "Guarde los bloques en el archivo.",
  loadTooltip: "Cargar bloques del archivo.",
  notificationTooltip: "Panel de notificaciones.",
  ErrorGET: "No se puede cargar el archivo solicitado. ",
  invalidDevice: "Dispositivo inválido.",
  languageTooltip: "Cambiar idioma.",
  noToolbox: "El dispositivo no tiene una toolbox.",
  networkTooltip: "Conectarse a través de la red  (WebREPL, https).",
  serialTooltip: "Conectarse a través de serial/USB (Web Serial API, http).",
  toolbarTooltip: "Barra de herramientas",
  wrongDevicePin: "Compruebe los pines, el dispositivo ha cambiado",
  notDefined: "no definido",
  editAsFileValue: "Editar como archivo",
  editAsFileTooltip: "Edite el código python y guárdelo en el dispositivo.",
  forumTooltip: "Foro de ayuda",
  blocksLoadedFromFile: "Bloques cargados desde el archivo '%1'.",
  deviceUnavailable: "Dispositivo '%1' no disponible."
};
