#!/bin/bash

# Script to deploy on GAE.

APP=./app.yaml
if ! [ -f $APP ] ; then
   echo $APP not found 1>&2
   exit 1
fi

PROJECT=bipes-271213
VERSION=37

echo 'Beginning deployment...'
#gcloud app deploy --project $PROJECT --version $VERSION --no-promote
gcloud app deploy --project $PROJECT --version $VERSION --promote
echo 'Deployment finished.'
